# Generated by Django 5.0.6 on 2024-07-12 21:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta_smartphones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphones',
            name='especificacion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='smartphones',
            name='posee_camara',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='smartphones',
            name='precio',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(2000)]),
        ),
    ]
